# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2b24f735a7061672fee996d25e588c39686f1bc533983201b35685c652e4fae1a2da5fb32feb086d6099085714634c0fba8388df024232b29d5ceec446092e1

test:
  secret_key_base: 34f167cdabd67cae2b107741ce766f6cdb06183543c69cfd44a0509f18bc21e59f1e80565903da5c9aae9ba40a8229652f13ade0dd56bc32712057e319e60ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
